## Created by UziPlex edit by MrFrips

version: 1.2

# Main Formating
chat:
    enabled: true
    format: "<player> → &r<message>"
    colored-chat:
        enabled: true
        permission: cf.colored
