## Created by UziPlex

version: 1.0

# Main Formating
# Read the docs which you can find on my
# spigot page!
chat:
    enabled: true
    format: "&7<player>: <message>"
    colored-chat:
        enabled: true
        permission: cf.colored
